### ISSUE TITLE
Can the atril icon be changed to differ from the evince icon?

### ISSUE THREAD

**Issue by william8000** [perberos/Mate-Desktop-Environment#101]
On Fedora 17, I have both atril and evince, and they use the same icon, so I have to guess to pick the right one.
On the mate desktop, atril looks ok but evince paints with old style square like it is missing a screen layout.
I thought that the evince icon was supposed to be a script "e".  Could atril have an "a" icon?

**Comment by perberos** [comment]
https://github.com/mate-desktop/mate-document-viewer/issues/6
