### ISSUE TITLE
'nyan cat' and potential copyright infringement

### ISSUE THREAD

**Issue by ghost** [perberos/Mate-Desktop-Environment#104]
Hi all,

I opened this bug report to request that it's evaluated the status of the 'nyan cat' and potential copyright infringements; Several documents online, blog posts and others seem to point that Nyan Cat is copyrighted; The animated gif holds one copyright, the music holds another copyright and the video has yet another copyright holder.

I would like to suggest that MATE contacts the copyright holders and get permission for the usage of 'nyan cat'; This might become a show stopper and not clear with distributions which have stronger commitments to the community; this can have negative impact on MATE deployment.

Please consider: https://bugzilla.redhat.com/show_bug.cgi?id=839851

Can we have an official statement from MATE towards this issue and sort this out for our downstreamers ?

**Comment by perberos** [comment]
time to drop nyancat

**Comment by szesch** [comment]
I agree.

**Comment by ghost** [comment]
You don't need to remove it; as long as you email the author and request permission; inform him that you will distribute a copy of the email with his permission with the sources and that will most likely allow it to stay.

Either way this needs a fix :)

**Comment by perberos** [comment]
trolling patents, we can not risk, for the sake of the distros.
if it were me, I would use a picture of micky mouse lol

**Comment by perberos** [comment]
sh-t miss the button

**Comment by imran-uk** [comment]
But "micky mouse" is owned by Disney. Use him and you have a Disney lawyer knocking on your door ;-)

I see in 1.4 that Nyancat was removed. No update here on what Christopher Torres said? I'd be suprised if he said no, not like he's making millions from it... or is he?

http://en.wikipedia.org/wiki/Nyan_Cat

**Comment by perberos** [comment]
gnucat
