### ISSUE TITLE
mate-display-manager shutdown problem

### ISSUE THREAD

**Issue by danielgomon** [perberos/Mate-Desktop-Environment#11]
Also when I use mate-display-manager, the shutdown option in the System menu (and the shutdown applet) doesn't show. Another issue is that I have to change the keyboard layout on every session start because mate-display-manager doesn't save my preferences.

Source = https://bbs.archlinux.org/viewtopic.php?pid=987797#p987797

**Comment by Cightline** [comment]
I don't see mate-display-manager in /usr/bin, so I don't know exactly what it does. My shutdown option/applet shows, you have added the applet to the panel right?

I get this when I run mate-keybinding-properties

(mate-keybinding-properties:8447): GLib-GObject-CRITICAL **: Object class EggCellEditableEventBox doesn't implement property 'editing-canceled' from interface 'GtkCellEditable'

I'll take a look at the source code
