### ISSUE TITLE
mate-keyring doesn't save password

### ISSUE THREAD

**Issue by danielgomon** [perberos/Mate-Desktop-Environment#12]
When I tried to use any app that need gksu (like gparted) mate-keyring doesn't save my password in the keyring, and I have to type it every time I used it.

**Comment by perberos** [comment]
Related, https://bbs.archlinux.org/viewtopic.php?pid=981975#p981975

**Comment by Cightline** [comment]
This might help

Gkr-Message: secret service operation failed: The algorithm 'dh-ietf1024-sha256-aes128-cbc-pkcs7' is not supported
glibtop: Non-standard uts for running kernel:
release 3.0-ARCH=3.0.0 gives version code 196608

**Comment by Cightline** [comment]
For reference, I've found the line in libmatekeyring/library/gkr-operation.c line 447 for secret service operation failed

**Comment by Cightline** [comment]
"The algorithm "" is not supported", is in Mate-Desktop-Environment/mate-keyring/daemon/dbus/gkd-secret-session.c
