### ISSUE TITLE
Wrong file associations in MATE

### ISSUE THREAD

**Issue by guidopola** [perberos/Mate-Desktop-Environment#15]
Ever since installing Mate, anything I download in Chromium wants to open in Firefox regardless of file associations...has anyone else observed this problem?

Source: https://bbs.archlinux.org/viewtopic.php?pid=990522#p990522

**Comment by guidopola** [comment]
I think you need to do something with "xdg-settings".

in ~/.xinitrc put "exec ck-launch-session mate-session"

Source: https://bbs.archlinux.org/viewtopic.php?pid=990717#p990717

**Comment by perberos** [comment]
The fix: https://bbs.archlinux.org/viewtopic.php?pid=1025671#p1025671

To fix the Chromium / xdg-open issue:

Open **/usr/bin/xdg-open** with text editor as root.

goto line **310**

search

``` sh
    if [ x"$KDE_FULL_SESSION" = x"true" ]; then DE=kde;
    elif [ x"$GNOME_DESKTOP_SESSION_ID" != x"" ]; then DE=gnome;
```

replace with

``` sh
    if [ x"$KDE_FULL_SESSION" = x"true" ]; then DE=kde;
    elif [ x"$GNOME_DESKTOP_SESSION_ID" != x"" ]; then DE=gnome;
    elif [ x"$MATE_DESKTOP_SESSION_ID" != x"" ]; then DE=mate;
```

goto line **383**

search

``` sh
open_gnome()
{
```

replace with

``` sh
open_mate()
{
    if gvfs-open --help 2>/dev/null 1>&2; then
        gvfs-open "$1"
    else
        mate-open "$1"
    fi

    if [ $? -eq 0 ]; then
        exit_success
    else
        exit_failure_operation_failed
    fi
}

open_gnome()
{
```

goto line **588**

search

``` sh
    lxde)
    open_lxde "$url"
    ;;
```

replace with

``` sh
    lxde)
    open_lxde "$url"
    ;;

    mate*)
    open_mate "$url"
    ;;
```

done.
