### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by LexMidnight** [perberos/Mate-Desktop-Environment#19]
This has been suggested on the ubuntuforums thread and it's something that should be done, sooner or later, since Ubuntu is the most used distro.

**Comment by AlexVSharp** [comment]
I'd say adding any PPA is a step in the right direction. More people will be willing to test it if the installation was simple.
Since I use Mint which is basically based on Ubuntu I have no problem with this suggestion. A repository is a must-have sooner or later.

**Comment by apcro** [comment]
This is being arranged: http://ubuntuforums.org/showpost.php?p=11403171&postcount=92

**Comment by perberos** [comment]
Amanas PPA is https://launchpad.net/~amanas/+archive/mate-desktop
