### ISSUE TITLE
MATE icon

### ISSUE THREAD

**Issue by perberos** [perberos/Mate-Desktop-Environment#2]
MATE need a kettle icon using the tango project icon guidelines.

Example:
http://1.bp.blogspot.com/_PFSh4ypP7lQ/TT15Vbc8xoI/AAAAAAAAAVE/HXtLBC-XZzE/s400/Le%2BCreuset%2Btrad%2Bstovetop%2Bkettle.jpg

**Comment by Sorrow5012** [comment]
I've tryed to create something...the colors isn't the same of Tango: the red is more dark and i've used black, not gray.
this is the icon in png and 500x500px for a better example.
http://img89.imageshack.us/img89/9659/imgstarter.png

**Comment by neocrust** [comment]
First variant of logo:
http://matede.googlecode.com/svn/logo/matelogo_1_prev.png

**Comment by LexMidnight** [comment]
This can be used as a base for a logo, or as a monochrome logo by itself
http://i41.tinypic.com/2ag2jwj.jpg

**Comment by perberos** [comment]
http://matsusoft.com.ar/projects/mate/mate.svg

**Comment by kmacphail** [comment]
I've been waiting for the Tango guidelines to be put back up for over a week now, are they located anywhere else or can anybody list them here.  If this is to use the Tango guidelines then I would like to know what they are. http://tango.freedesktop.org/Generic_Icon_Theme_Guidelines

**Comment by perberos** [comment]
Hello, this was reported in the mailing list > http://lists.freedesktop.org/archives/xdg/2011-November/012163.html

While, you can read it on web.archive > http://web.archive.org/web/20110615135909/http://tango.freedesktop.org/Tango_Desktop_Project

**Comment by perberos** [comment]
I recommend use the gnome color palette, for legacy.
http://developer.gnome.org/hig-book/2.32/design-color.html

**Comment by LexMidnight** [comment]
I like the http://matsusoft.com.ar/projects/mate/mate.svg logo

I use it as my Mint menu icon http://i41.tinypic.com/2s8rdrs.png

**Comment by RowenStipe** [comment]
Like the little  " >)) " (Bad ASCII art) looking logo but thought I might give a hand at making the kettle one here's my crack at it: http://rowenstipe.net/MATE/logo/MATe-concept.png
Uses the GNOME color palette at: http://developer.gnome.org/hig-book/2.32/design-color.html

**Comment by perberos** [comment]
the mate icon was picked

https://github.com/mate-desktop/mate-icon-theme/commit/bd045de03a7979f5ab16699e4c888b1e9259f858
https://github.com/mate-desktop/mate-icon-theme/commit/c7c80da1aaa36e26d4c1340c1475cb3e768dc358
