### ISSUE TITLE
segfault issue in caja related to libc6

### ISSUE THREAD

**Issue by apcro** [perberos/Mate-Desktop-Environment#23]
For some reason, running `caja` often results in a segfault.

A representative syslog entry:

```
shiny kernel: [85028.864740] caja[26816]: segfault at 34003260 ip 00007ff651ff91a4 sp 00007fffde617e00 error 4 in libc-2.13.so[7ff651fb0000+195000]
```

This may be unrelated to caja specifically. Investigation led me to replace libc6 manually, and delete the mime.cache file (suggestions from various discussion forums).

Segfault behaviour is inconsistent, sometimes occurring immediately on program execution, sometimes after the program has loaded and any other function is performed (typically pressing f3 to open the second pane)

**Comment by perberos** [comment]
Recently, on my Archlinux box, I am having same issue.
When I move files, copy, create, and sometimes on idle.

**Comment by apcro** [comment]
I have seen reference to this being related to a kernel bug in the 3.x branch, as it has also been seen with mount-nfs. I am not sure this is related to Mate or Caja at all.

**Comment by perberos** [comment]
it make sense, using nautilus on ubuntu 11.10 happens same thing.

**Comment by perberos** [comment]
I shall compile mate-file-manager-2011.9.26 to see if crash happens.

**Comment by perberos** [comment]
it crash too :/

**Comment by perberos** [comment]
I had not luck to solve this problem. It's on libc.

**Comment by perberos** [comment]
Amanas descubrió que PPA no le permitia crear el paquete de 64bits, entonces lo corrigió cambiando g_format_size_for_display por g_format_size. Pero no lo ha probado.

http://developer.gnome.org/glib/2.30/glib-Miscellaneous-Utility-Functions.html#g-format-size-for-display

**Comment by perberos** [comment]
Fix applied, thanks Amanas.
https://github.com/perberos/mate-desktop-environment/commit/1497454ac74ee74fb550f3c03c10e5daf7bab690
