### ISSUE TITLE
mate-settings-daemon sometimes uses 100% CPU

### ISSUE THREAD

**Issue by apcro** [perberos/Mate-Desktop-Environment#24]
mate-settings-daemon soetimes uses 100% CPU (1 of 8 cores). This behaviour most often happens after resuming from suspend or making appearance changes. Manually stopping the process resolves the issue.

Investigation into this led to the git source issue (#22)

**Comment by perberos** [comment]
closing due old.
I wish had more details about how to reproduce it.

Open a new ticket if it still happens.
