### ISSUE TITLE
mate-theme depends on gtk2-engines-2

### ISSUE THREAD

**Issue by apcro** [perberos/Mate-Desktop-Environment#26]
Manually compiling and installing from http://ftp.gnome.org/pub/gnome/sources/gtk-engines/2.20/ into a .deb indicates that the required library is provided by gtk2-engines 1:2.20.2-0ubuntu1, however configuration throws a depends error:

```
configure: error: Package requirements (gtk+-2.0 >= 2.0.0   gdk-pixbuf-2.0 >= 2.0.0   gtk-engines-2 >= 2.15.3 ) were not met:

No package 'gtk-engines-2' found
```

**Comment by szesch** [comment]
I believe you need the file /usr/lib/pkgconfig/gtk-engines-2.pc, which no longer exists, if I remember correctly.

Perberos has it uploaded here: http://matsusoft.com.ar/repository/ubuntu/gtk-engines-2.pc.

Hope that helps.

**Comment by perberos** [comment]
On ubuntu, the file was removed. On debian, it's still there.

**Comment by apcro** [comment]
replacing gtk-engines-2.pc with the content of the file listed above solved the issue.
