### ISSUE TITLE
Notification Area icons are not transparent

### ISSUE THREAD

**Issue by benbristow** [perberos/Mate-Desktop-Environment#27]
I'm not 100% certain this is a bug with all themes, but at least with the 'Elementary' GTK theme, the notification areas are not transparent and show a white background.

Here's an example with wicd:
http://i.imgur.com/QZFXo.png

**Comment by perberos** [comment]
Hello, It's a issue with a class name called "MatePanelApplet". You must find the word "PanelApplet" on the GtkRC file of the theme and change it for "MatePanelApplet".

More info in the wiki https://github.com/Perberos/Mate-Desktop-Environment/wiki/Gtk-themes

But we are searching a way to fix it. Still no luck.

**Comment by perberos** [comment]
This was fixed. yay

https://github.com/perberos/Mate-Desktop-Environment/commit/598f0f109784f3788b78ac34e8da07847ee3a89e
