### ISSUE TITLE
mate-control-center distro/ubuntu/prerm

### ISSUE THREAD

**Issue by apcro** [perberos/Mate-Desktop-Environment#29]
The prerm file in distro/ubuntu calls

```
usr/sbin/mateconfpkg --uninstall ${pkgname}
```

which causes an error on install.

It should be 

```
/usr/sbin/mateconfpkg --uninstall ${pkgname}
```

(assuming `mateconfpkg` has been installed in `/usr/sbin`)

**Comment by perberos** [comment]
Done, thanks.

https://github.com/Perberos/Mate-Desktop-Environment/commit/1059d0e1e76b6919a38b34422f304b79694572a2
