### ISSUE TITLE
Making New Control PANEL

### ISSUE THREAD

**Issue by perberos** [perberos/Mate-Desktop-Environment#3]
Añadido por **Alexander Dragan** hace 25 días.

`It's siple "New Desktop - New and BEtter Controls" Let's Make new more comfort control Panel, then GNOME 2 has. In GNOME 2 Nowbody use it. We must fix that , and make realy useful and comfort MainPanel to manage the settings. Share your's varians, please.`

**Comment by Cightline** [comment]
So your wanting a new control panel that people like and use?

**Comment by perberos** [comment]
Well, we already have the mate-control-center. It works perfectly fine. But it is more easy to access the control panel items from the menu panel.

I am closing this because there is not much motivation.
