### ISSUE TITLE
Links to mate.org

### ISSUE THREAD

**Issue by fiedukow** [perberos/Mate-Desktop-Environment#30]
In some places there are (dead) links to mate.org
eg. art.mate.org/backgrounds in background selection window.
Probably they should be removed or changed to correct ones.

**Comment by perberos** [comment]
done

https://github.com/Perberos/Mate-Desktop-Environment/commit/6c903b83a35f6757c524b19b80f383c02dbe5bf3
https://github.com/Perberos/Mate-Desktop-Environment/commit/2db7fa5b6c2d7422d529a6eff2b84d840f2ed214
https://github.com/Perberos/Mate-Desktop-Environment/commit/664e6d1cb85c20a1090ab17be4cf5c88f2df7105
https://github.com/Perberos/Mate-Desktop-Environment/commit/d33e160a5c737a102a974bbd161f3b6ef54a59cf
