### ISSUE TITLE
files in conflict with gnome 2

### ISSUE THREAD

**Issue by stefano-k** [perberos/Mate-Desktop-Environment#38]
I installed mate on debian sid (with packages on my repository) together with gnome2.

Those 3 files are in conflict with gnome 2:

/usr/share/applications/network-scheme.desktop
/usr/share/applications/keybinding.desktop
/usr/share/dbus-1/services/org.freedesktop.Notifications.service

E: /var/cache/apt/archives/caja_1.0.0-2_i386.deb: tentata sovrascrittura di "/usr/share/applications/network-scheme.desktop" presente anche nel pacchetto nautilus 2.32.2.1-1
E: /var/cache/apt/archives/mate-control-center_1.0.0-2_i386.deb: tentata sovrascrittura di "/usr/share/applications/keybinding.desktop" presente anche nel pacchetto capplets-data 1
E: /var/cache/apt/archives/mate-notification-daemon_1.0.0-2_i386.deb: tentata sovrascrittura di "/usr/share/dbus-1/services/org.freedesktop.Notifications.service" presente anche nel pacchetto notification-daemon 0.5.0-2

**Comment by perberos** [comment]
done, thanks

https://github.com/perberos/Mate-Desktop-Environment/commit/5e44d84a3ddaed2e931ca9a7d083300199aecf3d
https://github.com/perberos/Mate-Desktop-Environment/commit/3fa480d3f25cba6ada16f122c6d0ebe06dc21784
https://github.com/perberos/Mate-Desktop-Environment/commit/fb8cd383b21a00d1b278b101be2c23a0217200b4

**Comment by perberos** [comment]
< stefano-k > perberos: about mate-keyring, it builds /usr/include/mategcr and /usr/include/gp11
< stefano-k > the last one is not renamed
< stefano-k > and also it builds /usr/lib/pkgconfig/gcr-0.pc and /usr/lib/pkgconfig/gp11-0.pc
< perberos > mate-keyring use gschemas
< stefano-k > and also /usr/share/gtk-doc/html/gp11 and /usr/share/gtk-doc/html/gcr :-P

**Comment by perberos** [comment]
done

https://github.com/perberos/Mate-Desktop-Environment/commit/eb635804fef025952133bdaeb3b41d2867ec385e
https://github.com/perberos/Mate-Desktop-Environment/commit/ebd4a9bf6a6a0a5629b5697d6833a22fbf14a012
