### ISSUE TITLE
mate-document-viewer

### ISSUE THREAD

**Issue by szesch** [perberos/Mate-Desktop-Environment#44]
Does not recognize pdf files. https://bbs.archlinux.org/viewtopic.php?pid=1016505#p1016505

Segfault (no stack trace). https://bbs.archlinux.org/viewtopic.php?pid=1016606#p1016606

**Comment by perberos** [comment]
`Does not recognize pdf files.`
this can be solved with recompile.

**Comment by perberos** [comment]
Segfault related https://github.com/perberos/mate-document-viewer/issues/1
