### ISSUE TITLE
mate-panel: fish applet doesnt work

### ISSUE THREAD

**Issue by stefano-k** [perberos/Mate-Desktop-Environment#47]
I tried to build mate-panel again, I got ever same issue: cpu at 100% and no applet shown. I tried debian and ubuntu, same issue on both.

**Comment by stefano-k** [comment]
just an update. I recompiled the old source again (1.0.2) and I got the same issue! So maybe the cause is another library involved in compilation. For example, I see that since yesterday debian wheezy got an update in libgtk (http://packages.qa.debian.org/g/gtk+2.0.html).

**Comment by stefano-k** [comment]
hi perberos. I recompiled the 1.0.0 label tag version. In that version the fish applet works.

I noticed that also workspace selector works in the 1.0.0 and doesnt works in the following commits.

maybe the solution of the issue #27 is the cause of this problem?

**Comment by perberos** [comment]
so, it was a mateconf schema problem?

**Comment by stefano-k** [comment]
yes. I close the issue. thanks
