### ISSUE TITLE
Ustedes usan mas que uno idioma en <<Migrating>>.  Is this project going to run in English or Spanish?

### ISSUE THREAD

**Issue by ghost** [perberos/Mate-Desktop-Environment#48]

**Comment by perberos** [comment]
feel free to translate it and move spanish texts to << Migrating.es >>

**Comment by ghost** [comment]
I have put in attempted translations for the Minimalism page.  I left the original Spanish on the page.

**Comment by ghost** [comment]
I also changed English part of "Minimalism Extremist".

**Comment by perberos** [comment]
Thankyou.
