### ISSUE TITLE
Using nautilus

### ISSUE THREAD

**Issue by perberos** [perberos/Mate-Desktop-Environment#5]
I've been using nautilus-elementary-bzr (from AUR) but i can't remove mate-file-manager due to dependencies and don't know the best way to set nautilus as the default file manager.

Source: https://bbs.archlinux.org/viewtopic.php?pid=987514#p987514

**Comment by danielgomon** [comment]
@Perberos can you fork the "nautilus-elementary" instead of the "classic nautilus". I think it would be nicer for all the Mate  DE users.

**Comment by perberos** [comment]
this issue was fixed
https://github.com/mate-desktop/mate-control-center/commit/06d81df2871a25a93cdf7cffaf87f5cd4f15fe84

@danielgomon: I can't do that.
