### ISSUE TITLE
Can't control banshee using panel applet or fn key

### ISSUE THREAD

**Issue by LexMidnight** [perberos/Mate-Desktop-Environment#51]
Can't control banshee using panel applet or function key combos. I'm using Mate in Linux Mint 12.

**Comment by perberos** [comment]
it is related #55 ?

**Comment by LexMidnight** [comment]
I think it's not, but I'm not too sure...

I can't really remember the model of my laptop, but its keyboard looks like this one http://www.notebookreview.com/assets/32706.jpg

Fn+F11 should lower the volume, but it does not
Fn+F12 should increase it, but it does not
Fn+left arrow/right arrow should play previous/next song, up is stop and down is play/pause

None of them is working

**Comment by perberos** [comment]
confirmed, volume control by key is not working

**Comment by perberos** [comment]
Packing issue. missing --enable-pulse flag.

**Comment by lucus** [comment]
This is still an issue for me on Linux Mint 12, mint-meta-mate version 2011-12-2.
How can I fix it?

**Comment by szesch** [comment]
Your using an old version of the packages.

http://wiki.mate-desktop.org/download#ubuntu

**Comment by lucus** [comment]
szesch, that fixed the volume controls, but play/pause and previous/next song still do not work.

**Comment by thatsmydoing** [comment]
I think this has to do with Banshee using Gnome Settings Daemon to set the keyboard shortcuts, but since Mate uses a different namespace, it can't find the service so it doesn't get access to the play/pause and previous/next.

**Comment by quequotion** [comment]
All media keys were broken when gnome-settings-daemon dropped support for them.

To restore the origninal functionality, gnome provides gnome-fallback-media-keys-helper.

How is Mate working around this?
