### ISSUE TITLE
Lockscreen keyboard shortcut doesn't work on Ubuntu 11.10

### ISSUE THREAD

**Issue by jlelli** [perberos/Mate-Desktop-Environment#53]
Hitting Control+Alt+L on Ubuntu 11.10 doesn't lock the screen as supposed to do. I've tried changing shortcut with no luck.
Moreover, if I lock the screen using the menu option, MATE seems to use gnome3 locking functionality (same gnome3 black lock screen and same unlock dialog).

**Comment by stefano-k** [comment]
I have same issue. But I dont know if it's a debian issue or an upstream issue.

**Comment by ghost** [comment]
However, there is a debian sid...
waiting for patch

**Comment by perberos** [comment]
do you need mate-screensaver for screenlocking

keybinding issue related: https://github.com/perberos/Mate-Desktop-Environment/issues/55

**Comment by quequotion** [comment]
Was this fixed in mate-screensaver by replacing gnome's missing dbus service?

Because that's why it didn't work.
