### ISSUE TITLE
alt+prtscn

### ISSUE THREAD

**Issue by mockturtl** [perberos/Mate-Desktop-Environment#57]
I don't see a listing for _mate-screenshot_ in the README.

[screencap](http://imageshack.us/photo/my-images/821/screencapk.jpg/)

**Comment by stefano-k** [comment]
mate-screenshots is in Mate-Extra/mate-utils package

**Comment by stefano-k** [comment]
if you are using mint, apt-get install mate-utils

**Comment by mockturtl** [comment]
Sorry for the delay -- hard drive is failing on me.  Will verify and close ASAP.

**Comment by mockturtl** [comment]
Verified.

**Comment by stefano-k** [comment]
Thanks :)
