### ISSUE TITLE
wine != mate in debian 

### ISSUE THREAD

**Issue by ghost** [perberos/Mate-Desktop-Environment#58]
When you install Wine 1.2.3 shows an error saying that wine trying to overwrite a file that is in mimeinfo.cache package mate-control-center and the installation fails
on the other DE there is no such ...

**Comment by stefano-k** [comment]
where did you get wine 1.2.3?

**Comment by perberos** [comment]
try get last .deb of mate-control-center

**Comment by ghost** [comment]
the problem is solved
