### ISSUE TITLE
(REQUEST) mate-file-manager-elementary 

### ISSUE THREAD

**Issue by danielgomon** [perberos/Mate-Desktop-Environment#59]
Can you fork nautilus-elementary to give the chance to use it in MATE and LinuxMint?

This have been suggested in the ArchLinux forums:

https://bbs.archlinux.org/viewtopic.php?pid=983323#p983323

https://bbs.archlinux.org/viewtopic.php?pid=987509#p987509

https://bbs.archlinux.org/viewtopic.php?pid=1001736#p1001736

**Comment by perberos** [comment]
Hello, I can not fork nautilus-elementary. But I can try to add some options on the mate-file-manager to make the possibility to looks like nautilus-elementary.

Please, open a new issue ticket explain what is the change that you want.

**Comment by perberos** [comment]
continued on #62
