### ISSUE TITLE
disk mounting

### ISSUE THREAD

**Issue by perberos** [perberos/Mate-Desktop-Environment#6]
I'm having problems with disk mounting (Not Authorized). I've added my user to all the groups; still not working. Any suggestions??? 

Source: https://bbs.archlinux.org/viewtopic.php?pid=987509#p987509

**Comment by danielgomon** [comment]
Yes I'm having this problem with all disk mounting. HAL it's already installed (and already added to rc.conf). I can mount disks only when I start session as root (I refer to disks mount with the Places menu, with a single click). I've add my user to ALL the groups (I see the groups with # cat /etc/group |cut -d: -f1): No luck.

Source: https://bbs.archlinux.org/viewtopic.php?pid=987797#p987797

**Comment by Cightline** [comment]
Please follow the instructions on,https://wiki.archlinux.org/index.php/GNOME_Tips#Turn_off_Authentication_needed_to_mount_internal_drive_in_Nautilus

**Comment by perberos** [comment]
Not sure if related http://forum.sabayon.org/viewtopic.php?f=86&t=23612

**Comment by Cightline** [comment]
Thats the exact same thing as I posted.

**Comment by perberos** [comment]
El problema parece estar en la parte donde se muestra la ventana de elevación de privilegios. Todavia no he revisado nada.

**Comment by perberos** [comment]
I've fixed it during the migration of code. On v2011.9.26
If it conflict again, please open a new Issue.
