### ISSUE TITLE
can't compile python-mate on fedora 16

### ISSUE THREAD

**Issue by raveit65** [perberos/Mate-Desktop-Environment#61]
Hi,
if i try to compile python-mate i get this error.

[rave@mother python-mate]$ ./waf configure
ERROR:root:/media/Programme/Linux/Mate-Desktop/Mate-Extra/python-mate/wscript:45: error: No module named _mate

python-corba is installed.
What can i do to resolve this error.?
If you need more info let me know.

All other package of the mate desktop exept 'mintmenu', i can install on fedora 16.
Nice desktop, thx for yor work an thx for helping.

**Comment by perberos** [comment]
waf? use:

./configure --prefix=/usr --sysconfdir=/etc \
        --localstatedir=/var --disable-static \
        --enable-mate \
        --enable-mateui \
        --enable-matecanvas \
        --enable-matevfs \
        --enable-matevfsmatecomponent \
        --enable-pyvfsmodule \
        --enable-mateconf \
        --enable-matecomponent_activation \
        --enable-matecomponent \
        --enable-matecomponentui

**Comment by raveit65** [comment]
Hi,
thx for helping.
If i used the configure option, 

[rave@mother python-mate]$ ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static --enable-mate --enable-mateui --enable-matecanvas --enable-matevfs --enable-matevfsmatecomponent --enable-pyvfsmodule --enable-mateconf --enable-matecomponent_activation --enable-matecomponent --enable-matecomponentui

i get this message at the end of configure.

The following modules will be built:

mate
mate.ui
matecanvas
matevfs
matevfs.matecomponent
mate-vfs python module support
mateconf
matecomponent
matecomponent.activation
matecomponent.ui

The following modules will NOT be built:

---

**\* WARNING: You are using a deprecated build system (autotools).
**\*          You should be using WAF instead; see the file INSTALL.WAF.
**\*          The autotools build system will be removed in a future version.

---

In this case the make command fails.

Making all in mate
make[2]: Entering directory `/media/Programme/Linux/Mate-Desktop/Mate-Extra/python-mate/mate'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -pthread -DHAVE_CONFIG_H -I. -I.. -I/usr/include/python2.7 -I/usr/include/python2.7 -pthread -I/usr/include/pygtk-2.0 -I/usr/include/gtk-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -DMATECORBA2=1 -D_REENTRANT -pthread -I/usr/include/libmate-2.0 -I/usr/include/matecorba-2.0 -I/usr/include/mateconf/2 -I/usr/include/mate-vfs-2.0 -I/usr/lib64/mate-vfs-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmatecomponent-2.0 -I/usr/include/matecomponent-activation-2.0   -lm -Wall -std=c9x -fno-strict-aliasing -MT _mate_la-matemodule.lo -MD -MP -MF .deps/_mate_la-matemodule.Tpo -c -o _mate_la-matemodule.lo`test -f 'matemodule.c' || echo './'`matemodule.c
mv -f .deps/_mate_la-matemodule.Tpo .deps/_mate_la-matemodule.Plo
mv: Aufruf von stat für „.deps/_mate_la-matemodule.Tpo“ nicht möglich: Datei oder Verzeichnis nicht gefunden
make[2]: *** [_mate_la-matemodule.lo] Fehler 1
make[2]: Leaving directory`/media/Programme/Linux/Mate-Desktop/Mate-Extra/python-mate/mate'
make[1]: **\* [all-recursive] Fehler 1
make[1]: Leaving directory `/media/Programme/Linux/Mate-Desktop/Mate-Extra/python-mate'
make: **\* [all] Fehler 2

In english this means it doesn't find  „.deps/_mate_la-matemodule.Tpo

**Comment by raveit65** [comment]
Hi.
do you need more info's to help me?
Is this a fedora problem?

**Comment by perberos** [comment]
in theory it should compile, but I do not know why it do not generate the file _.deps/_mate_la-matemodule.Tpo_

**Comment by raveit65** [comment]
I've download new packages of the mate-desktop yesterday and the make error is gone. Maybe the package was defective.
But now i can't compile mate-menu-editor and python-caja.

mate-menu-editor:
./configure --prefix=/usr libdir=/usr/lib64 --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --localstatedir=/var

ends in

checking for ALACARTE... no
configure: error: Package requirements (libmate-menu >= 2.27.92) were not met:

Requested 'libmate-menu >= 2.27.92' but version of libmate-menu is 1.1.1

python-caja:
./configure --prefix=/usr libdir=/usr/lib64 --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --localstatedir=/var

ends in

checking for CAJA_PYTHON... no
configure: error: Package requirements (pygtk-2.0 >= 2.8.0
                                   pygobject-2.0 >= 2.16.0
                                   mate-python-2.0 >= 2.12.0
                                   libcaja-extension >= 2.22.0) were not met:

Requested 'mate-python-2.0 >= 2.12.0' but version of MATE-python is 1.1.0
Requested 'libcaja-extension >= 2.22.0' but version of libcaja-extension is 1.1.0

I think this is a package problem with the new 1.1.0 version.

**Comment by raveit65** [comment]
same problem with mate-policykit

checking for MATECONF... no
configure: error: Package requirements (mateconf-2.0 >= 2.8) were not met:

Requested 'mateconf-2.0 >= 2.8' but version of mateconf is 1.1.0

Is there a forum where i can get help with the mate-desktop?

**Comment by szesch** [comment]
Hi, we haven't changed the version information in the configuration files for anything in https://github.com/mate-desktop/Mate-Extra yet. That's what's causing the problem.

**Comment by raveit65** [comment]
That's easy, i changed the configuration files and i can install python-caja and mate-menu-editor.  :)
But mate-policykit i can't compile because after changing the configuration files, the compiler asked for polkit-dbus and polkit-grant.
Fedora changed from policykit to polkit since fedora 13.
In the new version there is no polkit-dbus and polkit-grant, so it's impossible to compile mate-policykit on fedora 16.

Thx for helping and merry Christmas

Wolfgang Ulbrich, berlin

Edit:
I see there is a package mate-polkit, so it's no need to install mate-policykit. :)
