### ISSUE TITLE
Problem with mate-settings-daemon

### ISSUE THREAD

**Issue by subchee** [perberos/Mate-Desktop-Environment#68]
mate-settings-daemon does not handle media keys on my laptop (hardware volume up,down,mute) and on at least one other person's PC.

It could be because  media_keys plugin is missing and mate-settings-daemon does not start media_keys manager.

I gathered outputs from the followings:
gnome-settings-daemon --debug (gnome3)  : http://paste.debian.net/149818/
mate-settings-daemon --no-daemon --debug : http://paste.debian.net/149819/
gnome-settings-daemon --nodaemon --debug (gnome2) : http://paste.debian.net/149820/

The first two outputs were  made on this system: Debian Wheezy i386 (up-to-date) with MATÉ and Gnome3 installed / Lenovo ThinkPad T61 / Intel GMA965
The last one: Debian Squeeze i386 (up-to-date) with Gnome2 / Lenovo ThinkPad T61 / Intel GMA965

**Comment by perberos** [comment]
yes, media_keys plugin

**Comment by subchee** [comment]
Arch Linux is also affected, media_keys plugin is not compiled with mate-settings-daemon.
I tried to recompile mate-settings-daemon (v1.1.0 from git) on Arch. Output of configure script: http://pastebin.com/6gvcBFxN
It compiles but media_keys plugin is still missing. I also tried to compile the plugin alone but the .libs directory remains empty.

**Comment by stefano-k** [comment]
This issue is fixed in tridex (debian/ubuntu) repository. Version 1.1.0-4 of mate-settings-daemon package.

**Comment by perberos** [comment]
@subchee install pulseaudio and use --enable-pulse

**Comment by subchee** [comment]
@stefano-k : thanks, I tried the updated version on Debian Wheezy and it really works
@perberos : thanks, I succed to compile with pulse on Arch. Now I'd like to compile mate-media on Arch to get a volume-manager applet wich works with mate-settings-daemon (it seems volti does not).
