### ISSUE TITLE
mate-calc, mate-utils and mate-system-tools to AUR

### ISSUE THREAD

**Issue by perberos** [perberos/Mate-Desktop-Environment#7]
Can anyone upload the PKGBUILD's for mate-calc, mate-utils and mate-system-tools to AUR?? It would be nice! :P

Source: https://bbs.archlinux.org/viewtopic.php?pid=987509#p987509

**Comment by danielgomon** [comment]
Any news??

**Comment by perberos** [comment]
done

mate-system-monitor https://aur.archlinux.org/packages.php?ID=53260
mate-calc https://aur.archlinux.org/packages.php?ID=52323

mate-system-tools was not added to AUR because system-tools-backends disapear from arch repo. But PKGBUILD is on mate-system-tools source.
