### ISSUE TITLE
mate-power-preferences using deprecated gtk-2 functions

### ISSUE THREAD

**Issue by amitkr** [perberos/Mate-Desktop-Environment#70]
# FUNCTIONS:

gtk_combo_box_append_text
gtk_widget_hide_all

configure.ac
-DGTK_DISABLE_DEPRECATED causes preprocessor to hide those declarations/definitions
# GTK+ Lib

 [amitkr@psyche]:~$ pkg-config --modversion --cflags --cflags-only-I --libs-only-l --libs-only-L gtk+-2.0
2.24.8
-I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12  -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0
# ERROR

...
...
gcc -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -DMATECORBA2=1 -I/usr/include/libwnck-1.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/startup-notification-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/mateconf/2 -I/usr/include/matecorba-2.0 -I/usr/include/mate-keyring-1   -DGSEAL_ENABLE -pthread -I/usr/include/unique-3.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12    -pthread -I/usr/include/gtk-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -D_REENTRANT -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12    -DI_KNOW_THE_DEVICEKIT_POWER_API_IS_SUBJECT_TO_CHANGE -pthread -I/usr/include/libupower-glib -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -DBINDIR=\"/usr/bin\" -DSBINDIR=\"/usr/sbin\" -DMATELOCALEDIR=\""/usr/share/locale"\" -DDATADIR=\"/usr/share\" -DPREFIX=\""/usr"\" -DSYSCONFDIR=\""/etc"\" -DLIBDIR=\""/usr/lib64"\" -DVERSION="\"1.1.0\"" -DGPM_DATA=\"/usr/share/mate-power-manager\" -DGTKBUILDERDIR=\"/usr/share/mate-power-manager\" -DUP_DISABLE_DEPRECATED -DEGG_LOG_FILE=\""/tmp/gpm.log"\" -DEGG_VERBOSE="\"GPM_VERBOSE\"" -DEGG_LOGGING="\"GPM_LOGGING\"" -DEGG_CONSOLE="\"GPM_CONSOLE\"" -I..   -DG_DISABLE_SINGLE_INCLUDES -DGTK_DISABLE_SINGLE_INCLUDES -DG_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -DGDK_DISABLE_DEPRECATED -DGDK_MULTIHEAD_SAFE -DGTK_MULTIHEAD_SAFE -DGSEAL_ENABLE -g -fexceptions -Werror -Wall -Wcast-align -Wno-uninitialized -Wmissing-declarations -Wpointer-arith -Wcast-align -Wwrite-strings -Winit-self -Wreturn-type -Wformat-nonliteral -Wformat-security -Wmissing-include-dirs -Wmissing-format-attribute -Wclobbered -Wempty-body -Wignored-qualifiers -Wtype-limits -Wdeclaration-after-statement -Wshadow -Winline -Wmissing-parameter-type -Woverride-init -Wno-strict-aliasing  -g -O2 -MT mate_power_preferences-gpm-prefs-core.o -MD -MP -MF .deps/mate_power_preferences-gpm-prefs-core.Tpo -c -o mate_power_preferences-gpm-prefs-core.o `test -f 'gpm-prefs-core.c' || echo './'`gpm-prefs-core.c
gpm-prefs-core.c: In function ‘gpm_prefs_setup_action_combo’:
gpm-prefs-core.c:363:4: error: implicit declaration of function ‘gtk_combo_box_append_text’ [-Werror=implicit-function-declaration]
gpm-prefs-core.c: In function ‘prefs_setup_ac’:
gpm-prefs-core.c:690:3: error: implicit declaration of function ‘gtk_widget_hide_all’ [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors

**Comment by amitkr** [comment]
After compiling with gtk+-[23].0 and without GTK_DISABLE_DEPRECATED 

[amitkr@psyche]:~$ mate-power-preferences

Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap

**Comment by amitkr** [comment]
[amitkr@psyche]:~$ uname -a
Linux psyche 3.1.2-1.fc16.x86_64 #1 SMP Tue Nov 22 09:00:57 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux

[amitkr@psyche]:~$ cat /etc/redhat-release 
Fedora release 16 (Verne)

**Comment by szesch** [comment]
I've fixed the gtk_widget_hide_all deprecation in gpm-prefs-core.c. Haven't gotten to the other yet.

**Comment by perberos** [comment]
never forget to add links
https://github.com/mate-desktop/mate-power-manager/commit/3893856a1e22cb62a9d36eca5ab96284859d0d19
https://github.com/mate-desktop/mate-power-manager/commit/67bb8c1d1446c4056fed6832ecfde5f74660ce4f

**Comment by samtygier** [comment]
rest should be fixed by
https://github.com/mate-desktop/mate-power-manager/commit/30cc6ca0c463d9e2233947f3231399f2d9f64667

**Comment by amitkr** [comment]
thanks all, i was able to successfully compile it.
