### ISSUE TITLE
Ctrl+Z feature in Caja (undo the latest action)

### ISSUE THREAD

**Issue by omega3** [perberos/Mate-Desktop-Environment#74]
Could you please implement Ctrl+Z feature in Caja (undo the latest action). It is in Nautilus Elementary 2.32.2. It's very useful feature and I miss it very much in Mate.

**Comment by stefano-k** [comment]
I'll try to implement it

**Comment by stefano-k** [comment]
implemented: http://forums.mate-desktop.org/viewtopic.php?f=17&t=2
now, I'm testing it well

**Comment by stefano-k** [comment]
packaged in caja 1.1.1
