### ISSUE TITLE
"Open as administrator" missing in Caja

### ISSUE THREAD

**Issue by KirkM** [perberos/Mate-Desktop-Environment#76]
I'm just recommending that "Open as administrator" be added into Caja's right-click context menu for files and folders if it hasn't been considered yet. It's been available to nautilus via the 'nautilus-gksu' package for quite awhile now. Hoping this is due to come in soon.

**Comment by stefano-k** [comment]
this may need a little work:

from http://www.nongnu.org/gksu/ :
  gksu is being replaced by gksu PolicyKit, please take a look at http://live.gnome.org/gksu

**Comment by perberos** [comment]
stefano-k say: (ps. you can close this https://github.com/perberos/Mate-Desktop-Environment/issues/76, now we have caja-gksu)
