### ISSUE TITLE
ITP: Alacarte->Mila

### ISSUE THREAD

**Issue by oz123** [perberos/Mate-Desktop-Environment#78]
Hi Everyone, 
Just to save efforts and double works. Since I can program better in python then in C, I decided to help with this little package.
I converted Alacarte to Mila (the Hebrew word for "Word"). The package is now compatible with  MATE-DE, but there are some small issues. 
I will upload the sources to my git later tonight or tomorrow.

Cheers, 
Oz

**Comment by stefano-k** [comment]
where did you take source?
we have already it: https://github.com/mate-desktop/Mate-Extra/tree/master/mate-menu-editor (with the name Alacarte).

**Comment by oz123** [comment]
he he, duplicate work from me ... i took the Debian sources from wheezy and converted them. 
I have changed the build files and some stuff inside.

**Comment by stefano-k** [comment]
join on irc #mate to not duplicate work :)

**Comment by oz123** [comment]
well, I should, you are right. But it was still a good exercise on building a Debian package :-) so the effort is not wasted.

**Comment by oz123** [comment]
@stefano-k , mate-menu-editor, isn't packed yet. I can't find it in the repo. am I right ? I still see a point actually, in not having the Alacarte for MATE...

**Comment by stefano-k** [comment]
mate-menu-editor packaged as 'mozo'
