### ISSUE TITLE
caja-share

### ISSUE THREAD

**Issue by ghost** [perberos/Mate-Desktop-Environment#87]
nautilus-share lets you share folder in nautilus via samba.
caja is missing the extension

latest tridex repos.

**Comment by benpicco** [comment]
I already ported it to mate
https://github.com/benpicco/caja-share

**Comment by ghost** [comment]
well thank you but its not in the repo
http://mate.karapetsas.com/

**Comment by szesch** [comment]
https://github.com/mate-desktop/caja-share

Package forthcoming.

**Comment by benpicco** [comment]
If you need Japanese translation: http://git.gnome.org/browse/nautilus-share/commit/?id=acabd5fc75153fd43440f04c3cedc9b5b3d05567

**Comment by ghost** [comment]
can you have alook at cardapio-gnomepanel. idid not manage to port it myself... i could give you 10 euro via paypal.

**Comment by benpicco** [comment]
I've added the necessary changes to cardapio
https://code.launchpad.net/~benpicco/cardapio/mate

**Comment by ghost** [comment]
awesome.i ve compiled and tested it. "session buttons"(cardapio properties) and "edit menus" (mozo and alacarte installed) dont not work. 
and all control center things and settings are from gnome 3 instead of mate.
you made my day

**Comment by szesch** [comment]
This has now been renamed from caja-share to mate-file-manager-share for consistency reasons.
