### ISSUE TITLE
Changing how quickly the taskbar appears

### ISSUE THREAD

**Issue by lucus** [perberos/Mate-Desktop-Environment#96]
I have a hidden taskbar and I want it to appear instantly when I hover my mouse over it, but there is a slight delay of around a second. Is there a way to customise this? If not, could it be implemented?
Linux Mint 12, MATE 1.2

**Comment by szesch** [comment]
We no longer use this issue tracker.

https://github.com/perberos/Mate-Desktop-Environment/issues/92

**Comment by lucus** [comment]
A reboot fixed this.
